# Generated by Django 2.1.2 on 2018-10-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherToday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
