# Generated by Django 2.1.2 on 2018-11-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherToday', '0002_auto_20181028_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
